# This workflow will build and test multiple .NET projects using a matrix strategy
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: Build .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        project:
          - ProfanityFilter.Action.Tests
          - ProfanityFilter.Client.Tests
          - ProfanityFilter.Services.Tests
          - ProfanityFilter.Common.Tests

    steps:
    - uses: actions/checkout@main
    - name: Setup .NET
      uses: actions/setup-dotnet@main
      with:
        global-json-file: ./global.json

    - name: Restore dependencies
      run: dotnet restore

    - name: Test — ${{ matrix.project }}
      run: |
        # Publish the test project.
        dotnet publish --configuration Release tests/${{ matrix.project }}/

        # Change to the test project directory.
        cd artifacts/publish/${{ matrix.project }}
        ls
        cd ./release_linux-x64

        # Call test executable.
        ./${{ matrix.project }}